###
author = "charlesrocket"
base_url = "https://halve-z.netlify.app"
default_language = "en"
description = "Two-column retro theme for Zola"
theme = "halve-z"
title = "Halve-Z Zola theme"

build_search_index = true
compile_sass = true
generate_feeds = true
generate_sitemap = true
minify_html = true

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[search]
include_content = true
include_description = true
include_path = false
include_title = true
index_format = "elasticlunr_json"

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  {theme = "OneHalfDark", filename = "syntax-theme-dark.css"},
  {theme = "OneHalfLight", filename = "syntax-theme-light.css"},
]
render_emoji = false

[slugify]
anchors = "safe"
paths = "safe"
taxonomies = "safe"

[extra]
csp = true
locale = "en_US"
logo = "icon-192x192.png"
manifest = "manifest.json"
read_time = true
toc = true

[extra.placeholders]
subtitle = false
tags = false

[extra.home]
footer = true
glitch = false
logo = {enabled = false, height = "100", width = "100"}
subtitle = "Thaj Afsal"
title = "Afsal Thaj"

[extra.images]
categories = [
  {name = "media", image = "https://raw.githubusercontent.com/bearcott/8bit-art/master/cities/urban.gif"},
] 
default_post = "bk-prk.png" #https://failsafe.monster/bk-prk.jpg
home = "c1tyh4ll.png" #https://failsafe.monster/c1tyh4ll.png
post_list = "bk-prk.png" #https://failsafe.monster/bk-prk.jpg

[extra.menu]
links = [
  {name = "Code", url = "/projects/"},
]
posts = true
posts_label = "Posts"

[extra.footer]
author = true
copyright = true
enabled = true
hash = true
links = [
  {name = "posts", url = "/posts/"},
]
stack = true

[extra.social]
bitbucket = "user_name"
codeberg = "username"
email = "afsal.taj06@gmail.com"
github = "afsalthaj"
instagram = "afzal.taj"
linkedin = "afsal-thaj-10ab2842"
twitter = "@afsal2"

[extra.mastodon]
author = "@user@server"

[extra.comments]
system = "giscus"

[extra.comments.cactus]
guest_posting = true
page_size = 10
site = "site_name"
update_interval = 0

[extra.comments.giscus]
category = "posts"
category_id = "DIC_kwDOOyR-Hc4CqtM-"
lang = "en"
mapping = "title"
reactions = "1"
repo = "afsalthaj/my-site-comments"
repo_id = "R_kgDOOyR-HQ"
strict = "0"
